# Generated by Django 4.0.6 on 2022-07-18 05:37

from django.db import migrations, models
import django.db.models.deletion
import equipment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mask', equipment.models.MaskField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype')),
            ],
        ),
    ]
